### ISSUE TITLE
Hibernate

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim2#34]
Prebacite hibernate konfiguraciju u src/main/resources kako bi testovi radili

FAQ: http://c2.etf.unsa.ba/mod/resource/view.php?id=40725

**Comment by dzbricic** [comment]
Hvala. Je li sad ok? 

Poslano preko Samsung Mobile uređaja

-------- Izvorna poruka --------
Šalje: Dean Cupovic notifications@github.com 
Datum:  
To: SoftverInzenjeringETFSA/SI2014Tim2 SI2014Tim2@noreply.github.com 
Naslov: [SI2014Tim2] Hibernate (#34) 

Prebacite hibernate konfiguraciju u src/main/resources kako bi testovi radili

FAQ: http://c2.etf.unsa.ba/mod/resource/view.php?id=40725

**Comment by deancupovic** [comment]
Nije.
Niste popravili reference u hibernate.cfg.xml
Sada je dovoljno "AdministratorHibernate.hbm.xml" umjesto "ba/etf/unsa/si/KlaseHibernate/AdministratorHibernate.hbm.xml"

**Comment by dzbricic** [comment]
Je li sad ok? Hvala Vam puno.

Poslano preko Samsung Mobile uređaja

-------- Izvorna poruka --------
Šalje: Dean Cupovic notifications@github.com 
Datum:  
To: SoftverInzenjeringETFSA/SI2014Tim2 SI2014Tim2@noreply.github.com 
Kopija: Dzenana Bricic dzenanabricic@hotmail.com 
Naslov: Re: [SI2014Tim2] Hibernate (#34) 

Nije.
Niste popravili reference u hibernate.cfg.xml
Sada je dovoljno "AdministratorHibernate.hbm.xml" umjesto "ba/etf/unsa/si/KlaseHibernate/AdministratorHibernate.hbm.xml"

**Comment by deancupovic** [comment]
Prošli su testovi, tako da jeste.
