### ISSUE TITLE
Login forma - neusaglašenost sa UIS

### ISSUE THREAD

**Issue by aklacar1** [SoftverInzenjeringETFSA/SI2014Tim2#36]
Komponenta : QuickSheet - Login

Commit : 0ef691c215126b0f76d3cdd13e281ca7fe74bbb6

Opis problema :
U UISu nema Dugme za prijavu i CheckBox za odabir da li je korisnik administrator ili ne :
UIS : http://prntscr.com/79krxi
Login Forma : http://prntscr.com/79ku4s

Koraci za reproduciranje problema:
Kompajlirati aplikaciju (Run as java application)

**Comment by hcustovic1** [comment]
U odnosu na UIS je dodano dugme za prijavu, jer je očigledno da je unutar dokumenta to bio lapsus, a checkbox je izbačen.
commit: 3fc46c026b
