### ISSUE TITLE
Osnovni layout za Administratora - nausaglasenost sa UIS

### ISSUE THREAD

**Issue by aklacar1** [SoftverInzenjeringETFSA/SI2014Tim2#39]
Komponenta : QuickSheet - Administrator

Commit : 0ef691c215126b0f76d3cdd13e281ca7fe74bbb6

Opis problema :
UIS dizajn i dizajn forme se razlikuju:
http://prntscr.com/79kzim
http://prntscr.com/79kzpa

Koraci za reproduciranje problema:
Kompajlirati aplikaciju (Run as java application)

**Comment by hcustovic1** [comment]
Tokom razvoja aplikacije, ustanovljeno je da nema smisla da administrator ima mogućnost popunjavanja timesheet-a. Tako da su tabovi vezani za tu aktivnost izbačeni.
