### ISSUE TITLE
Kreiranje novog korisnika bug / Prikaz arhiviranih korisnika

### ISSUE THREAD

**Issue by aklacar1** [SoftverInzenjeringETFSA/SI2014Tim2#40]
Komponenta : QuickSheet - Admnistrator

Commit : 0ef691c215126b0f76d3cdd13e281ca7fe74bbb6

Opis problema :
Nakon brisanja korisnika, nemoguće je dodati novog korisnika sa istim username čak i ako je taj korisnik upravo bio izbrisan:
http://prntscr.com/79l3mp

Ujedno kako ne brise korisnika iz baze, ne prikazuje istog korisnika kao arhiviranog korisnika :
Baza : http://prntscr.com/79l8dr
Forme : http://prntscr.com/79l8mh

Koraci za reproduciranje problema:
Kompajlirati aplikaciju (Run as java application)
Otvoriti Korisnici tab
Dodati novog validnog korisnika
Napraviti pretragu na istom tabu za tog korisnika
Izbrisati istog korisnika kojeg smo ranije dodali
Pokusati ponovo dodati istog korisnika
Pokusati izvrsiti pretragu arhiviranih korisnika

**Comment by dzbricic** [comment]
Prilikom brisanje korisnika, isti se arhivira, a ne briše iz baze podataka. U slučaju da korisnika želimo da vratimo, njegov stari username bit će validan.
