### ISSUE TITLE
Korisnici pretraga po prezimenu

### ISSUE THREAD

**Issue by aklacar1** [SoftverInzenjeringETFSA/SI2014Tim2#42]
Komponenta : QuickSheet - Admnistrator

Commit : 0ef691c

Opis problema :
Pretraga korisnika po prezimenu nije implementirana:
Forme : http://prntscr.com/79l9ow
Baza : http://prntscr.com/79l9vh

Koraci za reproduciranje problema:
Kompajlirati aplikaciju (Run as java application)
Otvoriti Korisnici tab
U polju za pretragu promijeniti u Prezime
Pretraziti korisnike sa validnim prezimenom

**Comment by hcustovic1** [comment]
Unutar forme je obavljena pretraga arhiviranih korisnika, a zaposlenik sa prezimenom Hajdarević nije arhiviran, tako da i nije očekivano da se prikažu njegovi podaci.
