### ISSUE TITLE
Kreiranje novog korisnika - SRS

### ISSUE THREAD

**Issue by aklacar1** [SoftverInzenjeringETFSA/SI2014Tim2#44]
Komponenta : QuickSheet - Admnistrator

Commit : 0ef691c

Opis problema :
//Edit Podatci u Podaci  :)
Podaci koji se nalaze u SRSu se ne nalaze na formi za dodavanje novog korisnika i postavljenje novog passworda nije od strane sistema kako je opisano u SRSu, nego je od strane Administratora.

http://prntscr.com/79lp4m

Koraci za reproduciranje problema:
Kompajlirati aplikaciju (Run as java application)
Otvoriti Korisnici tab
Uporediti podatke sa SRSom

**Comment by ElmirHodzic** [comment]
Podaci*

**Comment by dzbricic** [comment]
ID nema smisla jer se automatski generiše i inkrementira. Ostala polja su dodana.
