### ISSUE TITLE
Modifikacija korisnika - SRS

### ISSUE THREAD

**Issue by aklacar1** [SoftverInzenjeringETFSA/SI2014Tim2#45]
Komponenta : QuickSheet - Admnistrator

Commit : 0ef691c

Opis problema :
Podaci koji se nalaze u SRSu se ne nalaze na formi za modifikaciju korisnika.

http://prntscr.com/79lrvf

Koraci za reproduciranje problema:
Kompajlirati aplikaciju (Run as java application)
Otvoriti Korisnici tab
Uporediti podatke sa SRSom

**Comment by dzbricic** [comment]
ID nema smisla jer se automatski generiše i inkerementira. Radno mjesto je riješeno preko checkboxa.  Broj telefona i email je dodan.
