### ISSUE TITLE
Pretraga i pregled korisnika - SRS

### ISSUE THREAD

**Issue by aklacar1** [SoftverInzenjeringETFSA/SI2014Tim2#46]
Komponenta : QuickSheet - Admnistrator

Commit : 0ef691c

Opis problema :
Pretraga korisnika nije po svim poljima kako je opisano u SRSu.

http://prntscr.com/79ludm

Koraci za reproduciranje problema:
Kompajlirati aplikaciju (Run as java application)
Otvoriti Korisnici tab
Uporediti podatke sa SRSom

**Comment by dzbricic** [comment]
Nema smisla da pretraga bude po svim poljima.
