### ISSUE TITLE
Historija gresaka

### ISSUE THREAD

**Issue by ElmirHodzic** [SoftverInzenjeringETFSA/SI2014Tim2#49]
Commit ID: 0ef691c

Opis problema:
Nakon izazvane greške na jednom tabu greška se ne briše ni nakon promjene tabova

http://pokit.org/get/?f429fc891f328fc6521035baea48033c.png

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "QuickSheet-1.0-jar-with-dependencies".
2. Unijeti login podatke za administratora i check-irati administratora.
3. Izazovite gresku na tabu odjeli.npr klik na dugme "Dodaj" u dodaj novi odjel
4. Izazovite gresku na tabu projekti.npr klik na dugme "Pretrazi objekat" u pretraga projekta

Dobijeni rezultat:
-Ako se ponovo vratite na tab odjeli ispisat ce vam gresku koju ste izazvali u koraku 3, ili ponovni klik na tab 4 vam prikazuje gresku u koraku 4

Očekivani rezultat:
-"Cista" forma bez gresaka

**Comment by dzbricic** [comment]
Ukoliko se napusti tab sa greškama, nakon povratka na isti smatramo da trebaju ostati podaci, da bi se isti napisali pravilno.
