### ISSUE TITLE
Visestruki prikaz odjela

### ISSUE THREAD

**Issue by ElmirHodzic** [SoftverInzenjeringETFSA/SI2014Tim2#50]
Commit ID: 0ef691c

Opis problema:
Moguce visestruko prikazati odjel

http://pokit.org/get/?d08900fb1ace9082c3aab0ab7d20a650.png

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "QuickSheet-1.0-jar-with-dependencies".
2. Unijeti login podatke za administratora i check-irati administratora.
3. U tabu Odjeli pretrazite odjel po nazivu
4. Kliknite na jedan odjel
5. Kliknite na prikazi odjel
6. Ponovo fokusirajte formu administratora
7. Kliknite ponovo na prikazi odjel

Dobijeni rezultat:
-Visestruki prikaz

Očekivani rezultat:
-Jedinstven prikaz uz onemogucavanje fokusa na administratorsku formu

**Comment by dzbricic** [comment]
Imali smo gorih bugova, ovo nismo stigli riješiti.
