### ISSUE TITLE
Nije omogućena odjava sa korisničkog računa

### ISSUE THREAD

**Issue by Irma12** [SoftverInzenjeringETFSA/SI2014Tim2#59]
Commit ID: 0ef691c

Opis problema:
Ukoliko se ulogujemo u sistem kao administrator nije vidljivo (ne postoji dugme) za odjavu sa računa

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "QuickSheet-1.0-jar-with-dependencies".
2. Unijeti login podatke za administratora i check-irati administratora.

Dobijeni rezultat:
http://prntscr.com/7b1piz

Očekivani rezultat:
Button na formi koji bi značio odjavu sa ovog računa

**Comment by edincongo** [comment]
Popravljeno
Commit ID: 68cc03c808c005a90c49ea64c19af2fe7a4284d5
