### ISSUE TITLE
Pogrešna poruka upozorenja

### ISSUE THREAD

**Issue by Irma12** [SoftverInzenjeringETFSA/SI2014Tim2#64]
Komponenta : QuickSheet - Administrator
Commit ID: 0ef691c

Opis problema:
Nakon unosa imena i passworda za Administratora i pokusaja prijave sa uncheked boxom Admin pojavi se poruka koja nije jasna i ne pokazuje da se mora checkirati box

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "QuickSheet-1.0-jar-with-dependencies".
2. Unijeti login podatke za administratore
3. Ostaviti checkbox Administrator prazno

Dobijeni rezultat:
http://prntscr.com/7b257o

Očekivani rezultat:
Poruka upozorenja ' Morate checkirati box'

**Comment by hcustovic1** [comment]
Ukoliko se korisnik prijavljuje kao administrator i ne označi checkbox za administratora, podrazumijeva se da se ne prijavljuje kao administrator.

**Comment by Irma12** [comment]
Gdje je to navedeno :S
