### ISSUE TITLE
Nema kursora na login formi kod unosa korisničkog imena

### ISSUE THREAD

**Issue by ghost** [SoftverInzenjeringETFSA/SI2014Tim2#65]
Komponenta: QuickSheet - Login
Commit ID: 09bf2ed

Opis problema:
Kod prijave korisnika, na login formi, u polju za unos korisničkog imena
ne vidi se kursor, što otežava manevrisanje unosom korisničkog imena ako se napravi neka greška u unosu.

Koraci za reporduciranje problema:
1. Pokrenuti desktop aplikaciju "QuickSheet" prema uputstvu.
2. Postaviti fokus na kontrolu za unos korisničkog imena
3. Početi kucati

Dobijeni rezultat:
    - U kontroli za unos korisničkog imena se ne prikazuje kursor

Očekivani rezultat:
    - U kontroli za unos korisničkog imena se treba prikazati kursor<

**Comment by hcustovic1** [comment]
-commit: f7ff8db7f9ed52fb23e2669ef2a2dad60a2c038b
