### ISSUE TITLE
Nemogućnost logovanja kao koordinator

### ISSUE THREAD

**Issue by ghost** [SoftverInzenjeringETFSA/SI2014Tim2#70]
Komponenta QuickSheet - Login
Commit ID: 09bf2ed

Opis problema:  
Nije moguće se logovati kao koordinator

Koraci za reporduciranje problema;
1. Pokrenuti desktop aplikaciju "QuickSheet" prema uputstvu.
2. Logovati se kao koordinator (npr username: lfazlic1, pass: ovojelejla).

Dobijeni rezultat:
    - http://pokit.org/get/?b1fe283e214982b1b6a47560410f0fe1.jpg

Očekivani rezultat:
    - Forma za koordinatora;

**Comment by hcustovic1** [comment]
commit: 51e6dab2ae
