### ISSUE TITLE
Ništa se ne dešava nakon slanja na reviziju

### ISSUE THREAD

**Issue by emina-saric** [SoftverInzenjeringETFSA/SI2014Tim2#76]
Komponenta:
QuickSheet - Zaposlenik - Tab "Moj Timesheet"

commit ID:
0ef691c

Opis problema:
Ništa se ne dešava nakon klika na dugme "Pošalji na reviziju", tako da se ne zna je li operacija uspjela.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "QuickSheet" prema uputstvu na linku.
2. Logovati se kao neki od zaposlenika.
3. Otvoriti tab "Moj Timesheet".
4. Izabrati jedan projekat.
5. Unijeti validne podatke o procentu završenosti, broju sati i ukupnom broju sati.
6. Kliknuti na "Pošalji na reviziju".

Dobijeni rezultat:
Sve ostaje isto.

Očekivani rezultat:
Potvrda da su podaci uspješno poslani na reviziju.

**Comment by hcustovic1** [comment]
#88
