### ISSUE TITLE
Slanje na reviziju, vrijednost JSpinnera

### ISSUE THREAD

**Issue by emina-saric** [SoftverInzenjeringETFSA/SI2014Tim2#78]
Komponenta:
QuickSheet - Zaposlenik - Tab "Moj timesheet"

commit ID:
0ef691c

Opis problema:
Kad se klikne dugme "Pošalji na reviziju", vrijednost ukupnog broja radnih sati se postavi na vrijednost unesenu u polje "Broj radnih sati".

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "QuickSheet" prema uputstvu na linku.
2. Logovati se kao neki od zaposlenika.
3. Otvoriti tab "Moj timesheet".
4. Unijeti vrijednosti u sva polja.
5. Kliknuti na dugme "Pošalji na reviziju".

Dobijeni rezultat:
Polje "Ukupan broj radnih sati" mijenja vrijednost na broj koji je unesen u polje "Broj sati".

Očekivani rezultat:
Polje "Ukupan broj radnih sati" povećava svoju vrijednost za broj koji je unesen u polje "Broj sati".

**Comment by hcustovic1** [comment]
Ukupan broj sati bi trebao samo replicirati broj sati unesenih pod "Broj sati".
