### ISSUE TITLE
Onemogucena odjava Administratoru

### ISSUE THREAD

**Issue by SaudinAdemovic** [SoftverInzenjeringETFSA/SI2014Tim2#79]
Komponenta QuickSheet -Administrator
Commit ID: 09bf2ed

Nakon prijave korisnika kao Administratr, nigdje u QuickSheet -Administrator ne postoji dugme za odjavu

Koraci za reporduciranje problema:

1.Pokrenuti desktop aplikaciju "QuickSheet" prema uputstvu.
2.Logovati se kao administrator

Dobijeni rezultat: 
http://pokit.org/get/?d3846dd418381dfe8d03c757b9b2db1b.jpg

Ocekivani rezultat:
Da postoji dugme za odjavu Administratora

**Comment by edincongo** [comment]
#59
