### ISSUE TITLE
Nemogucnost odjave Zaposlenika

### ISSUE THREAD

**Issue by SaudinAdemovic** [SoftverInzenjeringETFSA/SI2014Tim2#81]
Komponenta QuickSheet -Zaposlenik
Commit ID: 09bf2ed

Nakon prijave korisnika kao Zaposlenik, nigdje u QuickSheet -Zaposlenik ne postoji dugme za odjavu, da bi se prijavio neko sa drugim korisničkim računom mora skroz zatvoriti aplikaciju pa je opet pokrenuti

Koraci za reporduciranje problema:

1.Pokrenuti desktop aplikaciju "QuickSheet" prema uputstvu.
2.Logovati se kao Zaposlenik

Dobijeni rezultat: 
Nigdje ne postoji dugme za Odjavu
http://pokit.org/get/?95d6afb9edb90a6c64723f29fd191344.jpg

Ocekivani rezultat:
Da postoji dugme za odjavu Zaposlenika

**Comment by edincongo** [comment]
Popravljeno
Commit ID: 9b7e5c9b8a01fab4227fd10ddd029043b6049b52
