### ISSUE TITLE
Slanje na reviziju nejasno ponašanje

### ISSUE THREAD

**Issue by ElmirHodzic** [SoftverInzenjeringETFSA/SI2014Tim2#84]
Commit ID: 0ef691c

Opis problema:
Nejasno ponašanje nakon klika na dugme pošalji na reviziju

http://postimg.org/image/sbtzk8sjd/
http://postimg.org/image/8egmefrfz/

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "QuickSheet-1.0-jar-with-dependencies".
2. Unijeti login podatke za zaposlenika (imePrezime, lozinka11)
3.Na početnom tabu u numericupdown kontroli izaberite neki broj
4. Kliknite pošalji na reviziju

Dobijeni rezultat:
-Numericupdown se setuje na nulu i ne može se mijenjati i nakon svakog sljedećeg klika na pošalji na reviziju ništa se ne događa

Očekivani rezultat:
-Koncizan slijed događaja nakon klika na pošalji na reviziju uz adekvtnu interakciju.

**Comment by hcustovic1** [comment]
#88
