### ISSUE TITLE
Nejasan ishod 

### ISSUE THREAD

**Issue by Irma12** [SoftverInzenjeringETFSA/SI2014Tim2#88]
Commit ID: 0ef691c

Opis problema:
Nejasan ishod 

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "QuickSheet-1.0-jar-with-dependencies".
2. Unijeti login podatke za koordinatora
3. Prebaciti se na tab Moj Timesheet
4. Izabrati projekat 2
5. Unijesti podatke sa slike
6. Pritisnuti Pošalji na reviziju

Dobijeni rezultat:
http://prntscr.com/7b9uvk

Očekivani rezultat:
Poruka upozorenja ili uspješnog dodavanja

**Comment by hcustovic1** [comment]
Dodan je message box koji javlja da li je timesheet poslan uspješno na reviziju ili ne.
